{
 "title": "Trading Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "account_id",
    "label": "account_id",
    "query": "fc66cf9b-8fb8-4d9e-ba79-a5e8b87c5aa7"
   }
  ]
 },
 "panels": [
  {
   "title": "SBER свечи (10 мин)",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time_utc, open, high, low, close, volume FROM tinvest_candles WHERE \"interval\" = 10"
    }
   ]
  },
  {
   "title": "Текущий баланс портфеля",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time_utc, portfolio FROM portfolio_snapshots WHERE account_id = '$account_id' ORDER BY time_utc ASC "
    }
   ]
  },
  {
   "title": "Доходность портфеля",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT expected_yield, time_utc FROM portfolio_snapshots WHERE account_id = '$account_id' ORDER BY time_utc ASC "
    }
   ]
  },
  {
   "title": "Позиция SBER",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time_utc, balance FROM position_snapshots WHERE (account_id = '$account_id' AND instrument_uid = 'e6123145-9665-43e0-8413-cd61b8aa9b13') ORDER BY time_utc ASC "
    }
   ]
  },
  {
   "title": "Торговые сигналы",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT time_utc, quantity FROM signals WHERE time_utc >= '2024-12-26 17:00:00.000' ORDER BY time_utc ASC "
    }
   ]
  },
  {
   "title": "История доходности",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT time_utc, expected_yield FROM portfolio_snapshots WHERE account_id = '$account_id' ORDER BY time_utc DESC LIMIT 5000 "
    }
   ]
  },
  {
   "title": "Сделки",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT date, quantity, price, type FROM operations WHERE (account_id = '$account_id' AND operation_type <> 19) ORDER BY date DESC "
    }
   ]
  },
  {
   "title": "Комиссии брокера и биржи",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT date, payment FROM operations WHERE (operation_type = 19 AND account_id = '$account_id') ORDER BY date DESC "
    }
   ]
  },
  {
   "title": "Комиссии за все время",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(payment) FROM operations WHERE (account_id = '$account_id' AND operation_type = 19)"
    }
   ]
  },
  {
   "title": "Портфель без учета комиссий",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT portfolio FROM portfolio_snapshots WHERE account_id = '$account_id' ORDER BY time_utc DESC LIMIT 1\r\n"
    },
    {
     "rawSql": "SELECT SUM(payment) FROM operations WHERE (account_id = '$account_id' AND operation_type = 19)"
    },
    { "expression": "$A-$B", "type": "math" }
   ]
  }
 ]
}